events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Set client_max_body_size to 150M as required for asset transfers
    client_max_body_size 150M;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;
        
        # Redirection for captive portal
        error_page 404 =200 /index.html;

        # Android / Apple captive portal detection endpoints
        location /generate_204 { return 204; }
        location /gen_204 { return 204; }
        location /hotspot-detect.html { return 302 /; }

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
